version:  '2'
services:

  master:
    image: fineplace/hadoop1.2-node
    networks:
      default:
        ipv4_address: 172.16.0.110
    extra_hosts:
      - "slave1:172.16.0.111"
      - "slave2:172.16.0.112"
    hostname: master
    tty: true

  slave1:
    image: fineplace/hadoop1.2-node
    networks:
      default:
        ipv4_address: 172.16.0.111
    extra_hosts:
      - "master:172.16.0.110"
      - "slave2:172.16.0.112"
    hostname: slave1
    tty: true

  slave2:
    image: fineplace/hadoop1.2-node
    networks:
      default:
        ipv4_address: 172.16.0.112
    extra_hosts:
      - "master:172.16.0.110"
      - "slave1:172.16.0.111"
    hostname: slave2
    tty: true

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.0/16
        gateway: 172.16.0.250

